pipeline {
    agent any

    tools {
            nodejs 'Node16'
        }
    environment {
        AWS_CRED = 'aws_goexpert'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from GitHub
               git branch: 'main',
                   url: 'https://github.com/GC368/GoExpertsFrontend.git'
            }
        }

        stage('Build') {
            steps {
                // Install project dependencies
                sh 'npm install'
                // Run npm build
                sh 'npm run build'
            }
        }

        stage('Deploy to AWS') {
            steps {
                withAWS(credentials: AWS_CRED, region: 'us-east-1') {
                    sh 'aws s3 sync ./build/ s3://testuseast123/'
                    // withAWS(region: 'us-east-1', credentials: '923094287044') {
                    //     s3Upload(files: './build', bucket: 'testuseast123', path: 'path/on/s3')
                    // }
                }
            }
        }
    }
}

